### PR TITLE
Fix for #160 and #113

### LINKED ISSUE #160: Potential Memory Leak
I've been noticing an issue as of late that causes the game to take forever to save, causes players who are joined to be dropped from the game, and also causes the nanite factories to freeze up their production. My current guess is that the mod, namely the facilities themselves are causing a memory leak in the game. Sadly, i couldn't include last nights (early this morning) sessions nanite logs since it only keeps one copy, but i have included the logs for space engineers as well as my short play session just earlier.

The short play session wasn't experiencing quite the scale of issues i saw last night, but i was having some delay in the speed of the game save, and attempting to close the server/world to the main menu also softlocked the game, forcing me to close the game through task manager, of which it did not stop using system memory for a good 10 minutes.

One thing to note at this time, I do have multiple nanite facilities constructed (three). I mention this as I saw githubs mention issues with using multiple facilities. I will post more logs as I run more sessions that I experience issues with.

I will also make a thread reply on the Steam discussion page. Let me know if there is anything else i can do on my end to help track this issue down.

Pastebin links
https://pastebin.com/hScctf0v nanite log
https://pastebin.com/uv2uz3H0 part 1 of 8/4 2:56 am se log 
https://pastebin.com/E9uhGSVF part 2 of 8/4 2:56 am se log 
https://pastebin.com/R0L9ACPg 8/4 3:04 am se log
https://pastebin.com/UR5UC7iP 8/4 11:38 am se log (despite being a short session, this one forced me to close the game with task manager

### PR DESCRIPTION
**Pull request by stefan2200**
Might require some further testing but it worked for over 30 minutes on projection, construction, deconstruction and life support without any issues.
This merge should fix #160 and #113

### CODE REVIEW

**Comment by M0dEx** [comment]
Looks good to me.

I'm actually quite ashamed that I didn't find the time to get to the bottom of all the bugs, since I am still figuring out some personal stuff.

Thank you for this. I'll test this and merge it into the master branch.

**Comment by stefan2200** [comment]
Thanks for the quick reply!

Hopefully this merge fixes the issue because NCS is one of those essential late-game mods. 
But I'm still trying to figure out what caused the issue in the first place, it looks like the Parallel did not seem to like the `remove` list since m_particles contained over 60.000 entries after 40 minutes of playing. 

That is why I also implemented ```if (item != null) item.Unload();
if (m_particles != null && m_particles.Contains(item)) m_particles.Remove(item);``` since Remove removes the instance of item and not the value (null).

If I find the time I might look into some of the other open issues, especially #147 since that one starts to annoy me :)

Good luck testing!

**Comment by M0dEx** [comment]
Yeah, it is absolutely possible that the sheer amount of entries lagged the main-thread into oblivion. Doing it with Parallel.ForEach like this seems like a better way.

I also just found out that I cannot really test this myself, since I permanently moved to Linux (Windows sucks) and I can't get it to work here. The only thing I can do is just code in Rider.

**Comment by stefan2200** [comment]
Hmmm perhaps any other maintainers can take a look sometime, my NCS dev is working again so no hurry :)

**Comment by nukeguard** [comment]
thanks Stefan, I've checked the merge out and I have not been experiencing the save bug, I also don't have a world where that was happening, so if someone has a world with that problem, I can try it out.

**Pull request merged**
